### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by t-lo** [t-lo/mailserver#1]
- [x] add documentation on client set-up
- [x] add monitoring
- [x] add sanity check after initialisation
   - [x] check MX of `DOMAIN` and `ADDITIONAL_DOMAINS`
   - [x] check SPF and DKIM TXT records
- [x] add opendkim and opendmarc to set-up
